version: '3.4'

name: MiniTodo-Dev

services:
  rjsilvas.teste-dev:
    build:
      context: .
      dockerfile: src/Minitodo.API/Dockerfile    
    container_name: teste-dev
    depends_on:
      - database-dev
    ports:
      - "5000:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development   
  
  database-dev:
    image: mysql:8.0.22
    container_name: mysqldb-dev
    ports:
        - "3306:3306"
    expose: 
        - 3306
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - db-volume-dev:/var/lib/mysql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_TCP_PORT: 3306
        
volumes:
  db-volume-dev: 
