version: '3.4'

services:
  rjsilvas.teste:
    image: renatojsilvas/teste:latest
    container_name: teste
    ports:
      - "5000:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production   

