version: '3.4'

services:
  rjsilvas.teste:
    image: renatojsilvas/teste-dev:latest
    container_name: teste-dev
    ports:
      - "5001:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development    
