version: '3.4'

services:
  rjsilvas.teste:
    image: renatojsilvas/teste:dev
    container_name: teste
    ports:
      - "5001:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development    
