version: '3.4'

services:
  rjsilvas.teste:
    build:
      context: .
      dockerfile: src/Minitodo.API/Dockerfile    
    container_name: teste-dev
    ports:
      - "5001:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development    
