version: '3.4'

services:
  rjsilvas.teste:
    image: renatojsilvas/teste-staging:latest
    container_name: teste-staging
    ports:
      - "5001:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Staging    
