version: '3.4'

services:
  rjsilvas.teste:
    image: renatojsilvas/teste:latest
    container_name: teste
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=Production   

  database:
    image: mysql:8.0.22
    container_name: mysqldb
    ports:
        - "3306:3306"
    expose: 
        - 3306
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - db-volume:/var/lib/mysql
    restart: always
    environment: 
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_TCP_PORT: 3306
        
volumes:
  db-volume: 
